// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type Cargo struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type Empleado struct {
	ID          int64
	Nombre      string
	Apellido    string
	Salario     float64
	HorasSemana int64
	CargoID     int64
}
