// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const actualizarCargo = `-- name: ActualizarCargo :one
UPDATE cargos
SET nombre = ?, descripcion = ?
WHERE id = ?
RETURNING id, nombre, descripcion
`

type ActualizarCargoParams struct {
	Nombre      string
	Descripcion string
	ID          int64
}

func (q *Queries) ActualizarCargo(ctx context.Context, arg ActualizarCargoParams) (Cargo, error) {
	row := q.db.QueryRowContext(ctx, actualizarCargo, arg.Nombre, arg.Descripcion, arg.ID)
	var i Cargo
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const actualizarEmpleado = `-- name: ActualizarEmpleado :one
UPDATE empleados
SET nombre = ?, apellido = ?, salario = ?, horas_semana = ?, cargo_id = ?
WHERE id = ?
RETURNING id, nombre, apellido, salario, horas_semana, cargo_id
`

type ActualizarEmpleadoParams struct {
	Nombre      string
	Apellido    string
	Salario     float64
	HorasSemana int64
	CargoID     int64
	ID          int64
}

func (q *Queries) ActualizarEmpleado(ctx context.Context, arg ActualizarEmpleadoParams) (Empleado, error) {
	row := q.db.QueryRowContext(ctx, actualizarEmpleado,
		arg.Nombre,
		arg.Apellido,
		arg.Salario,
		arg.HorasSemana,
		arg.CargoID,
		arg.ID,
	)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Salario,
		&i.HorasSemana,
		&i.CargoID,
	)
	return i, err
}

const borrarCargo = `-- name: BorrarCargo :execrows
DELETE FROM cargos WHERE id = ?
`

func (q *Queries) BorrarCargo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarCargo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const borrarEmpleado = `-- name: BorrarEmpleado :execrows
DELETE FROM empleados WHERE id = ?
`

func (q *Queries) BorrarEmpleado(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarEmpleado, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarCargoPorID = `-- name: BuscarCargoPorID :one
SELECT id, nombre, descripcion FROM cargos
WHERE id = ?
`

func (q *Queries) BuscarCargoPorID(ctx context.Context, id int64) (Cargo, error) {
	row := q.db.QueryRowContext(ctx, buscarCargoPorID, id)
	var i Cargo
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const buscarEmpleadoPorID = `-- name: BuscarEmpleadoPorID :one
SELECT id, nombre, apellido, salario, horas_semana, cargo_id FROM empleados
WHERE id = ?
`

func (q *Queries) BuscarEmpleadoPorID(ctx context.Context, id int64) (Empleado, error) {
	row := q.db.QueryRowContext(ctx, buscarEmpleadoPorID, id)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Salario,
		&i.HorasSemana,
		&i.CargoID,
	)
	return i, err
}

const crearCargo = `-- name: CrearCargo :one
INSERT INTO cargos (nombre, descripcion)
VALUES (?, ?)
RETURNING id, nombre, descripcion
`

type CrearCargoParams struct {
	Nombre      string
	Descripcion string
}

func (q *Queries) CrearCargo(ctx context.Context, arg CrearCargoParams) (Cargo, error) {
	row := q.db.QueryRowContext(ctx, crearCargo, arg.Nombre, arg.Descripcion)
	var i Cargo
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const crearEmpleado = `-- name: CrearEmpleado :one
INSERT INTO empleados (nombre, apellido, salario, horas_semana, cargo_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, nombre, apellido, salario, horas_semana, cargo_id
`

type CrearEmpleadoParams struct {
	Nombre      string
	Apellido    string
	Salario     float64
	HorasSemana int64
	CargoID     int64
}

func (q *Queries) CrearEmpleado(ctx context.Context, arg CrearEmpleadoParams) (Empleado, error) {
	row := q.db.QueryRowContext(ctx, crearEmpleado,
		arg.Nombre,
		arg.Apellido,
		arg.Salario,
		arg.HorasSemana,
		arg.CargoID,
	)
	var i Empleado
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Apellido,
		&i.Salario,
		&i.HorasSemana,
		&i.CargoID,
	)
	return i, err
}

const listarCargos = `-- name: ListarCargos :many
SELECT id, nombre, descripcion FROM cargos
`

func (q *Queries) ListarCargos(ctx context.Context) ([]Cargo, error) {
	rows, err := q.db.QueryContext(ctx, listarCargos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cargo
	for rows.Next() {
		var i Cargo
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarEmpleados = `-- name: ListarEmpleados :many
SELECT id, nombre, apellido, salario, horas_semana, cargo_id FROM empleados
`

func (q *Queries) ListarEmpleados(ctx context.Context) ([]Empleado, error) {
	rows, err := q.db.QueryContext(ctx, listarEmpleados)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Empleado
	for rows.Next() {
		var i Empleado
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Salario,
			&i.HorasSemana,
			&i.CargoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
