// Code generated by sqlc. DO NOT EDIT.
package sqlcdb

// Estos structs los genera sqlc a partir de db/schema.sql. OJO: NO son los
// models del dominio. Fíjense en los tipos: ID y Stock son int64 (no int).
// Esa diferencia es la razón por la que el adaptador tiene que MAPEAR.

type Categoria struct {
	ID          int64
	Nombre      string
	Descripcion string
}

type Producto struct {
	ID          int64
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
}
