// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql
package sqlcdb

import "context"

const actualizarProducto = `-- name: ActualizarProducto :one
UPDATE productos
SET nombre = ?, precio = ?, stock = ?, categoria_id = ?
WHERE id = ?
RETURNING id, nombre, precio, stock, categoria_id
`

type ActualizarProductoParams struct {
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
	ID          int64
}

func (q *Queries) ActualizarProducto(ctx context.Context, arg ActualizarProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, actualizarProducto,
		arg.Nombre,
		arg.Precio,
		arg.Stock,
		arg.CategoriaID,
		arg.ID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const borrarProducto = `-- name: BorrarProducto :execrows
DELETE FROM productos WHERE id = ?
`

func (q *Queries) BorrarProducto(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, borrarProducto, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const buscarProductoPorID = `-- name: BuscarProductoPorID :one
SELECT id, nombre, precio, stock, categoria_id FROM productos
WHERE id = ?
`

func (q *Queries) BuscarProductoPorID(ctx context.Context, id int64) (Producto, error) {
	row := q.db.QueryRowContext(ctx, buscarProductoPorID, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const crearProducto = `-- name: CrearProducto :one
INSERT INTO productos (nombre, precio, stock, categoria_id)
VALUES (?, ?, ?, ?)
RETURNING id, nombre, precio, stock, categoria_id
`

type CrearProductoParams struct {
	Nombre      string
	Precio      float64
	Stock       int64
	CategoriaID int64
}

func (q *Queries) CrearProducto(ctx context.Context, arg CrearProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, crearProducto,
		arg.Nombre,
		arg.Precio,
		arg.Stock,
		arg.CategoriaID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Precio,
		&i.Stock,
		&i.CategoriaID,
	)
	return i, err
}

const listarProductos = `-- name: ListarProductos :many
SELECT id, nombre, precio, stock, categoria_id FROM productos
`

func (q *Queries) ListarProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listarProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Precio,
			&i.Stock,
			&i.CategoriaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
